# Generated by Django 2.2.3 on 2019-09-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_blogarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogArticle',
        ),
    ]
